# Конфигурация для spring + (в перспективе) postgresql

version: '3'
services:
  app-ktor:
    image: ok-marketplace-app-ktor-ktor:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: secret
      JWT_ISSUER: OtusKotlin
      JWT_CERT_URL: ""
